<a href="https://colab.research.google.com/github/sarunsmenon/tf_kaggle/blob/sarunsmenon/003_file_stratified_sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json
import pandas as pd
import numpy as np
import os
import shutil

In [ ]:
base_path = "C:/Nuras/Kaggle/Benetech Making Graphs/benetech-making-graphs-accessible/"
annotation_path =base_path + "train/annotations/"

In [ ]:
chart_dtl_lst =[]
for file_nm in os.listdir(annotation_path):
    file_data_dict = json.load(open(annotation_path+file_nm, "r"))
    chart_type = file_data_dict['chart-type']
    chart_name = file_nm.split(".")[0]
    chart_df = pd.DataFrame({'chart_type' : [chart_type], 'chart_name':[chart_name]} )
    chart_dtl_lst.append(chart_df)

In [ ]:
chart_dtl_df = pd.concat(chart_dtl_lst)

In [ ]:
chart_dtl_sample_df = chart_dtl_df.groupby('chart_type',group_keys=False).apply(lambda x:x.sample(frac= 0.1))

In [ ]:
chart_dtl_sample_df.groupby('chart_type',group_keys=False).count()

                chart_name
chart_type
dot                    513
horizontal_bar           7
line                  2494
scatter               1124
vertical_bar          1919

In [ ]:
chart_dtl_df.groupby('chart_type',group_keys=False).count()

                chart_name
chart_type
dot                   5131
horizontal_bar          73
line                 24942
scatter              11243
vertical_bar         19189

In [ ]:
chart_dtl_sample_df.set_index('chart_name').reset_index()

        chart_name    chart_type
0     fc0db250483c           dot
1     949595868777           dot
2     6e1e55043dcb           dot
3     56074ae7a64a           dot
4     fce8c3babf9e           dot
...            ...           ...
6052  f335495342ba  vertical_bar
6053  928ddcc056e4  vertical_bar
6054  5f27d3c2be9e  vertical_bar
6055  cc8f66b9bb8f  vertical_bar
6056  fa534b6aacd0  vertical_bar

[6057 rows x 2 columns]

In [ ]:
def sample_copy(chart_type , chart_name):
    if 'bar' in chart_type:
        prefix="bar"
    elif 'scatter' in chart_type:
        prefix="scatter"
    elif 'dot' in chart_type:
        prefix="dot"
    else:
        prefix="line"

    src_file = base_path + prefix+"_chart/"+chart_name+".jpg"
    dest_fldr = base_path + prefix+ "_chart_sample/"
    shutil.copy(src_file, dest_fldr)

In [ ]:
chart_dtl_sample_df.apply(lambda x : sample_copy(x['chart_type'], x['chart_name']), axis=1)

0    None
0    None
0    None
0    None
0    None
     ...
0    None
0    None
0    None
0    None
0    None
Length: 6057, dtype: object